#### Name: Nguyen Thi Thu Trang
#### Class: DSEB65A
#### Student ID: 11230595

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'student_name': ['Anne', 'Ben', 'Chloe', 'David', 'Grace', 'Henry', 'Kate', 'Liam', 'Mike', 'Nora'],

    'math_score': [8.5, 7.0, 9.0, 5.5, 6.5, 8.0, 7.5, 10.0, 4.0, 9.5],

    'physics_score': [7.5, 6.5, 8.0, 4.0, 5.0, 7.0, 8.5, 9.0, 5.0, 9.0],

    'chemistry_score': [8.0, 7.5, 8.5, 5.0, 6.0, 9.0, 9.0, 9.5, 4.5, 10.0],

    'attendance': ['Good', 'Good', 'Good', 'Average', 'Fair', 'Good', 'Fair', 'Good', 'Poor', 'Good']
}

df_students = pd.DataFrame(data)

In [3]:
df_students

  student_name  math_score  physics_score  chemistry_score attendance
0         Anne         8.5            7.5              8.0       Good
1          Ben         7.0            6.5              7.5       Good
2        Chloe         9.0            8.0              8.5       Good
3        David         5.5            4.0              5.0    Average
4        Grace         6.5            5.0              6.0       Fair
5        Henry         8.0            7.0              9.0       Good
6         Kate         7.5            8.5              9.0       Fair
7         Liam        10.0            9.0              9.5       Good
8         Mike         4.0            5.0              4.5       Poor
9         Nora         9.5            9.0             10.0       Good

##### **Exercise 1: Data Exploration and Selection**

In [4]:
# 1
df_students.describe()

       math_score  physics_score  chemistry_score
count   10.000000      10.000000        10.000000
mean     7.550000       6.950000         7.700000
std      1.862644       1.786524         1.917753
min      4.000000       4.000000         4.500000
25%      6.625000       5.375000         6.375000
50%      7.750000       7.250000         8.250000
75%      8.875000       8.375000         9.000000
max     10.000000       9.000000        10.000000

In [7]:
# 2
df_top5 = df_students.head(5)
df_top5

  student_name  math_score  physics_score  chemistry_score attendance
0         Anne         8.5            7.5              8.0       Good
1          Ben         7.0            6.5              7.5       Good
2        Chloe         9.0            8.0              8.5       Good
3        David         5.5            4.0              5.0    Average
4        Grace         6.5            5.0              6.0       Fair

In [9]:
# 3
df_top5['student_name'].loc[[0, 2, 4]]

0     Anne
2    Chloe
4    Grace
Name: student_name, dtype: object

##### **Exercise 2: Filtering with Complex Conditions**

In [23]:
# 1
df_reward = df_students[(df_students['math_score'] >= 8) & (df_students['physics_score'] >= 8)]
df_reward

  student_name  math_score  physics_score  chemistry_score attendance
2        Chloe         9.0            8.0              8.5       Good
7         Liam        10.0            9.0              9.5       Good
9         Nora         9.5            9.0             10.0       Good

In [25]:
# 2
df_needs_improvement = df_students[(df_students['chemistry_score'] < 5) | (df_students['attendance'] == 'Poor')]
df_needs_improvement

  student_name  math_score  physics_score  chemistry_score attendance
8         Mike         4.0            5.0              4.5       Poor

##### **Exercise 3: Creating New Columns from Arithmetic Operations**

In [28]:
# 1
df_students['average_score'] = round((df_students['math_score'] + df_students['physics_score'] + df_students['chemistry_score']) / 3, 1)
df_students

,student_name,math_score,physics_score,chemistry_score,attendance,average_score
0,Anne,8.5,7.5,8.0,Good,8.0
1,Ben,7.0,6.5,7.5,Good,7.0
2,Chloe,9.0,8.0,8.5,Good,8.5
3,David,5.5,4.0,5.0,Average,4.8
4,Grace,6.5,5.0,6.0,Fair,5.8
5,Henry,8.0,7.0,9.0,Good,8.0
6,Kate,7.5,8.5,9.0,Fair,8.3
7,Liam,10.0,9.0,9.5,Good,9.5
8,Mike,4.0,5.0,4.5,Poor,4.5
9,Nora,9.5,9.0,10.0,Good,9.5

In [29]:
# 2
df_students['math_std_diff'] = df_students['math_score'] - df_students['math_score'].mean()
df_students

,student_name,math_score,physics_score,chemistry_score,attendance,average_score,math_std_diff
0,Anne,8.5,7.5,8.0,Good,8.0,0.95
1,Ben,7.0,6.5,7.5,Good,7.0,-0.55
2,Chloe,9.0,8.0,8.5,Good,8.5,1.45
3,David,5.5,4.0,5.0,Average,4.8,-2.05
4,Grace,6.5,5.0,6.0,Fair,5.8,-1.05
5,Henry,8.0,7.0,9.0,Good,8.0,0.45
6,Kate,7.5,8.5,9.0,Fair,8.3,-0.05
7,Liam,10.0,9.0,9.5,Good,9.5,2.45
8,Mike,4.0,5.0,4.5,Poor,4.5,-3.55
9,Nora,9.5,9.0,10.0,Good,9.5,1.95

##### **Exercise 4: Sorting and Filtering**

In [30]:
# 1
sorted_df_students = df_students.sort_values(by='average_score', ascending=False)
sorted_df_students

,student_name,math_score,physics_score,chemistry_score,attendance,average_score,math_std_diff
7,Liam,10.0,9.0,9.5,Good,9.5,2.45
9,Nora,9.5,9.0,10.0,Good,9.5,1.95
2,Chloe,9.0,8.0,8.5,Good,8.5,1.45
6,Kate,7.5,8.5,9.0,Fair,8.3,-0.05
0,Anne,8.5,7.5,8.0,Good,8.0,0.95
5,Henry,8.0,7.0,9.0,Good,8.0,0.45
1,Ben,7.0,6.5,7.5,Good,7.0,-0.55
4,Grace,6.5,5.0,6.0,Fair,5.8,-1.05
3,David,5.5,4.0,5.0,Average,4.8,-2.05
8,Mike,4.0,5.0,4.5,Poor,4.5,-3.55

In [31]:
# 2 
top3_students = sorted_df_students.head(3)
top3_students

,student_name,math_score,physics_score,chemistry_score,attendance,average_score,math_std_diff
7,Liam,10.0,9.0,9.5,Good,9.5,2.45
9,Nora,9.5,9.0,10.0,Good,9.5,1.95
2,Chloe,9.0,8.0,8.5,Good,8.5,1.45

##### **Exercise 5: Applying Functions with .map()**

In [33]:
# 1
attendance_status = {
    'Good': 10,
    'Fair': 8,
    'Average': 6,
    'Poor': 3
}

In [35]:
# 2
df_students['attendance_score'] = df_students['attendance'].map(attendance_status)
df_students

,student_name,math_score,physics_score,chemistry_score,attendance,average_score,math_std_diff,attendance_score
0,Anne,8.5,7.5,8.0,Good,8.0,0.95,10
1,Ben,7.0,6.5,7.5,Good,7.0,-0.55,10
2,Chloe,9.0,8.0,8.5,Good,8.5,1.45,10
3,David,5.5,4.0,5.0,Average,4.8,-2.05,6
4,Grace,6.5,5.0,6.0,Fair,5.8,-1.05,8
5,Henry,8.0,7.0,9.0,Good,8.0,0.45,10
6,Kate,7.5,8.5,9.0,Fair,8.3,-0.05,8
7,Liam,10.0,9.0,9.5,Good,9.5,2.45,10
8,Mike,4.0,5.0,4.5,Poor,4.5,-3.55,3
9,Nora,9.5,9.0,10.0,Good,9.5,1.95,10

##### **Exercise 6: Applying Custom Functions with .apply()**

In [36]:
# 1
def calculate_gpa_4(score):
    return score / 10 * 4

In [38]:
# 2
df_students[['math_score', 'physics_score', 'chemistry_score']].apply(calculate_gpa_4)

   math_score  physics_score  chemistry_score
0         3.4            3.0              3.2
1         2.8            2.6              3.0
2         3.6            3.2              3.4
3         2.2            1.6              2.0
4         2.6            2.0              2.4
5         3.2            2.8              3.6
6         3.0            3.4              3.6
7         4.0            3.6              3.8
8         1.6            2.0              1.8
9         3.8            3.6              4.0

##### **Exercise 7: Correlation Analysis**

In [42]:
# 1
columns = ['math_score', 'physics_score', 'chemistry_score']
df_students[columns].corr()

                 math_score  physics_score  chemistry_score
math_score         1.000000       0.877327         0.922273
physics_score      0.877327       1.000000         0.943733
chemistry_score    0.922273       0.943733         1.000000

In [41]:
# 2
# Physics and Chemistry have the strongest linear correlation.

##### **Exercise 8: Ranking and Classification**

In [43]:
# 1
df_students['math_rank'] = df_students['math_score'].rank(ascending=False)
df_students

,student_name,math_score,physics_score,chemistry_score,attendance,average_score,math_std_diff,attendance_score,math_rank
0,Anne,8.5,7.5,8.0,Good,8.0,0.95,10,4.0
1,Ben,7.0,6.5,7.5,Good,7.0,-0.55,10,7.0
2,Chloe,9.0,8.0,8.5,Good,8.5,1.45,10,3.0
3,David,5.5,4.0,5.0,Average,4.8,-2.05,6,9.0
4,Grace,6.5,5.0,6.0,Fair,5.8,-1.05,8,8.0
5,Henry,8.0,7.0,9.0,Good,8.0,0.45,10,5.0
6,Kate,7.5,8.5,9.0,Fair,8.3,-0.05,8,6.0
7,Liam,10.0,9.0,9.5,Good,9.5,2.45,10,1.0
8,Mike,4.0,5.0,4.5,Poor,4.5,-3.55,3,10.0
9,Nora,9.5,9.0,10.0,Good,9.5,1.95,10,2.0

In [44]:
# 2
df_students[df_students['math_rank'].isin([1, 2, 3])]

,student_name,math_score,physics_score,chemistry_score,attendance,average_score,math_std_diff,attendance_score,math_rank
2,Chloe,9.0,8.0,8.5,Good,8.5,1.45,10,3.0
7,Liam,10.0,9.0,9.5,Good,9.5,2.45,10,1.0
9,Nora,9.5,9.0,10.0,Good,9.5,1.95,10,2.0

##### **Exercise 9: Arithmetic with fill_value**

In [45]:
# 1, 2, 3
math_bonus = pd.Series([0.5, 0.25, 0.5, 0, 0.25])
physics_bonus = pd.Series([0.25, 0.5, 0.5, 0.25, 0.5], index=range(5, 10))

In [47]:
# 4
df_students['new_math_score'] = df_students['math_score'].add(math_bonus, fill_value=0)
df_students

,student_name,math_score,physics_score,chemistry_score,attendance,average_score,math_std_diff,attendance_score,math_rank,new_math_score
0,Anne,8.5,7.5,8.0,Good,8.0,0.95,10,4.0,9.00
1,Ben,7.0,6.5,7.5,Good,7.0,-0.55,10,7.0,7.25
2,Chloe,9.0,8.0,8.5,Good,8.5,1.45,10,3.0,9.50
3,David,5.5,4.0,5.0,Average,4.8,-2.05,6,9.0,5.50
4,Grace,6.5,5.0,6.0,Fair,5.8,-1.05,8,8.0,6.75
5,Henry,8.0,7.0,9.0,Good,8.0,0.45,10,5.0,8.00
6,Kate,7.5,8.5,9.0,Fair,8.3,-0.05,8,6.0,7.50
7,Liam,10.0,9.0,9.5,Good,9.5,2.45,10,1.0,10.00
8,Mike,4.0,5.0,4.5,Poor,4.5,-3.55,3,10.0,4.00
9,Nora,9.5,9.0,10.0,Good,9.5,1.95,10,2.0,9.50

In [48]:
# 5
df_students['new_physics_score'] = df_students['physics_score'].add(physics_bonus, fill_value=0)
df_students

,student_name,math_score,physics_score,chemistry_score,attendance,average_score,math_std_diff,attendance_score,math_rank,new_math_score,new_physics_score
0,Anne,8.5,7.5,8.0,Good,8.0,0.95,10,4.0,9.00,7.50
1,Ben,7.0,6.5,7.5,Good,7.0,-0.55,10,7.0,7.25,6.50
2,Chloe,9.0,8.0,8.5,Good,8.5,1.45,10,3.0,9.50,8.00
3,David,5.5,4.0,5.0,Average,4.8,-2.05,6,9.0,5.50,4.00
4,Grace,6.5,5.0,6.0,Fair,5.8,-1.05,8,8.0,6.75,5.00
5,Henry,8.0,7.0,9.0,Good,8.0,0.45,10,5.0,8.00,7.25
6,Kate,7.5,8.5,9.0,Fair,8.3,-0.05,8,6.0,7.50,9.00
7,Liam,10.0,9.0,9.5,Good,9.5,2.45,10,1.0,10.00,9.50
8,Mike,4.0,5.0,4.5,Poor,4.5,-3.55,3,10.0,4.00,5.25
9,Nora,9.5,9.0,10.0,Good,9.5,1.95,10,2.0,9.50,9.50

##### **Exercise 10: Comprehensive Problem**

In [52]:
# 1
df_students['final_score'] = df_students['average_score'] * 0.8 + df_students['attendance_score'] * 0.2
df_students['final_score']

0    8.40
1    7.60
2    8.80
3    5.04
4    6.24
5    8.40
6    8.24
7    9.60
8    4.20
9    9.60
Name: final_score, dtype: float64

In [50]:
# 2
df_students['Result'] = df_students['final_score'].apply(lambda x: 'Pass' if x >= 5 else 'Fail')

In [51]:
# 3
df_students['Result'].value_counts()

Result
Pass    9
Fail    1
Name: count, dtype: int64