#### Name: Nguyen Thi Thu Trang
#### Class: DSEB65A
#### Student ID: 11230595
#### Homework 2

In [60]:
import pandas as pd

import numpy as np

from io import StringIO

In [61]:
# --- Dataset 1: Orders ---

# Simulates reading 'orders.csv'

order_data = """order_id,customer_id,product_id,order_date,quantity,price_per_item

101,C01,P01,2023-10-01,2,500

102,C02,P03,2023-10-01,1,Not Available

103,C01,P02,2023-10-02,5,150

104,C03,P01,2023-10-03,N/A,500

105,C02,P04,2023-10-04,3,2000

106,C04,P02,2023-10-05,1,150

107,C05,P05,2023-10-05,--,300

108,C03,P02,2023-10-06,2,150

"""

# --- Dataset 2: More Orders (for concatenation) ---

# Simulates another file with more orders

more_order_data = """order_id,customer_id,product_id,order_date,quantity,price_per_item

109,C01,P04,2023-10-07,1,2000

110,C04,P03,2023-10-08,2,1200

"""

# --- Dataset 3: Customers ---

# Simulates reading 'customers.csv'

customer_data = """customer_id,customer_name,city

C01,John Doe,New York

C02,Jane Smith,London

C03,Peter Jones,New York

C04,Susan Lee,Tokyo

C06,David Chen,Tokyo

"""

# --- Dataset 4: Products ---

# Simulates reading 'product_details.csv'

product_data = """product_id,product_name,category

P01,Laptop,Electronics

P02,Mouse,Electronics

P03,Book,Stationery

P04,Keyboard,Electronics

P05,Pen,Stationery

"""

In [62]:
# Create DataFrames

df_orders = pd.read_csv(StringIO(order_data))

df_more_orders = pd.read_csv(StringIO(more_order_data))

df_customers = pd.read_csv(StringIO(customer_data))

df_products = pd.read_csv(StringIO(product_data))

##### **Exercise 1: Load and Diagnose df_orders**

In [63]:
# 1
df_orders = pd.read_csv(StringIO(order_data), 
                       na_values=['Not Available', 'N/A', '--'])

df_orders

   order_id customer_id product_id  order_date  quantity  price_per_item
0       101         C01        P01  2023-10-01       2.0           500.0
1       102         C02        P03  2023-10-01       1.0             NaN
2       103         C01        P02  2023-10-02       5.0           150.0
3       104         C03        P01  2023-10-03       NaN           500.0
4       105         C02        P04  2023-10-04       3.0          2000.0
5       106         C04        P02  2023-10-05       1.0           150.0
6       107         C05        P05  2023-10-05       NaN           300.0
7       108         C03        P02  2023-10-06       2.0           150.0

In [64]:
# 2
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        8 non-null      int64
 1   customer_id     8 non-null      object
 2   product_id      8 non-null      object
 3   order_date      8 non-null      object
 4   quantity        6 non-null      float64
 5   price_per_item  7 non-null      float64
dtypes: float64(2), int64(1), object(3)
memory usage: 516.0+ bytes

##### **Exercise 2: Correcting Data Types**

In [65]:
# 1
df_orders['order_date'] = pd.to_datetime(df_orders['order_date'])
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        8 non-null      int64
 1   customer_id     8 non-null      object
 2   product_id      8 non-null      object
 3   order_date      8 non-null      datetime64[ns]
 4   quantity        6 non-null      float64
 5   price_per_item  7 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 516.0+ bytes

In [66]:
# 2
df_orders['quantity'] = df_orders['quantity'].astype('float64')
df_orders['price_per_item'] = df_orders['price_per_item'].astype('float64')
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        8 non-null      int64
 1   customer_id     8 non-null      object
 2   product_id      8 non-null      object
 3   order_date      8 non-null      datetime64[ns]
 4   quantity        6 non-null      float64
 5   price_per_item  7 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 516.0+ bytes

##### **Exercise 3: Detecting and Dropping Missing Data**

In [67]:
# 1
df_orders.isnull().sum()

order_id          0
customer_id       0
product_id        0
order_date        0
quantity          2
price_per_item    1
dtype: int64

In [68]:
# 2
df_orders = df_orders.dropna(subset=['price_per_item'])
df_orders

   order_id customer_id product_id order_date  quantity  price_per_item
0       101         C01        P01 2023-10-01       2.0           500.0
2       103         C01        P02 2023-10-02       5.0           150.0
3       104         C03        P01 2023-10-03       NaN           500.0
4       105         C02        P04 2023-10-04       3.0          2000.0
5       106         C04        P02 2023-10-05       1.0           150.0
6       107         C05        P05 2023-10-05       NaN           300.0
7       108         C03        P02 2023-10-06       2.0           150.0

##### **Exercise 4: Filling Missing Data (Imputation)**

In [69]:
# 1
df_orders['quantity'] = df_orders['quantity'].fillna(1)
df_orders

/var/folders/bg/hsvxykxj7yx0jz1nrhc3k6z40000gn/T/ipykernel_1136/1733444970.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_orders['quantity'] = df_orders['quantity'].fillna(1)

   order_id customer_id product_id order_date  quantity  price_per_item
0       101         C01        P01 2023-10-01       2.0           500.0
2       103         C01        P02 2023-10-02       5.0           150.0
3       104         C03        P01 2023-10-03       1.0           500.0
4       105         C02        P04 2023-10-04       3.0          2000.0
5       106         C04        P02 2023-10-05       1.0           150.0
6       107         C05        P05 2023-10-05       1.0           300.0
7       108         C03        P02 2023-10-06       2.0           150.0

In [70]:
# 2
df_orders['quantity'] = df_orders['quantity'].astype('int')
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        7 non-null      int64
 1   customer_id     7 non-null      object
 2   product_id      7 non-null      object
 3   order_date      7 non-null      datetime64[ns]
 4   quantity        7 non-null      int64
 5   price_per_item  7 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 392.0+ bytes

/var/folders/bg/hsvxykxj7yx0jz1nrhc3k6z40000gn/T/ipykernel_1136/81946157.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_orders['quantity'] = df_orders['quantity'].astype('int')

##### **Exercise 5: Concatenating Datasets**

In [71]:
# 1 2
df_orders = pd.concat([df_orders, df_more_orders], ignore_index=True)
df_orders

,order_id,customer_id,product_id,order_date,quantity,price_per_item
0,101,C01,P01,2023-10-01 00:00:00,2,500.0
1,103,C01,P02,2023-10-02 00:00:00,5,150.0
2,104,C03,P01,2023-10-03 00:00:00,1,500.0
3,105,C02,P04,2023-10-04 00:00:00,3,2000.0
4,106,C04,P02,2023-10-05 00:00:00,1,150.0
5,107,C05,P05,2023-10-05 00:00:00,1,300.0
6,108,C03,P02,2023-10-06 00:00:00,2,150.0
7,109,C01,P04,2023-10-07,1,2000.0
8,110,C04,P03,2023-10-08,2,1200.0

##### **Exercise 6: Merging Orders with Customers (One-to-Many Join)**

In [ ]:
# 1
df_orders = pd.merge(df_orders, df_customers, on='customer_id')
df_orders

,order_id,customer_id,product_id,order_date,quantity,price_per_item,customer_name,city
0,101,C01,P01,2023-10-01 00:00:00,2,500.0,John Doe,New York
1,103,C01,P02,2023-10-02 00:00:00,5,150.0,John Doe,New York
2,104,C03,P01,2023-10-03 00:00:00,1,500.0,Peter Jones,New York
3,105,C02,P04,2023-10-04 00:00:00,3,2000.0,Jane Smith,London
4,106,C04,P02,2023-10-05 00:00:00,1,150.0,Susan Lee,Tokyo
5,108,C03,P02,2023-10-06 00:00:00,2,150.0,Peter Jones,New York
6,109,C01,P04,2023-10-07,1,2000.0,John Doe,New York
7,110,C04,P03,2023-10-08,2,1200.0,Susan Lee,Tokyo

In [73]:
# 2
df_orders = pd.merge(df_orders, df_customers, on='customer_id', how='left')
df_orders

,order_id,customer_id,product_id,order_date,quantity,price_per_item,customer_name,city
0,101,C01,P01,2023-10-01 00:00:00,2,500.0,John Doe,New York
1,103,C01,P02,2023-10-02 00:00:00,5,150.0,John Doe,New York
2,104,C03,P01,2023-10-03 00:00:00,1,500.0,Peter Jones,New York
3,105,C02,P04,2023-10-04 00:00:00,3,2000.0,Jane Smith,London
4,106,C04,P02,2023-10-05 00:00:00,1,150.0,Susan Lee,Tokyo
5,107,C05,P05,2023-10-05 00:00:00,1,300.0,NaN,NaN
6,108,C03,P02,2023-10-06 00:00:00,2,150.0,Peter Jones,New York
7,109,C01,P04,2023-10-07,1,2000.0,John Doe,New York
8,110,C04,P03,2023-10-08,2,1200.0,Susan Lee,Tokyo

##### **Exercise 7: Merging with Product Details**

In [ ]:
# 1 2
df_merged = pd.merge(df_orders, df_products)
df_merged

,order_id,customer_id,product_id,order_date,quantity,price_per_item,customer_name,city,product_name,category
0,101,C01,P01,2023-10-01 00:00:00,2,500.0,John Doe,New York,Laptop,Electronics
1,103,C01,P02,2023-10-02 00:00:00,5,150.0,John Doe,New York,Mouse,Electronics
2,104,C03,P01,2023-10-03 00:00:00,1,500.0,Peter Jones,New York,Laptop,Electronics
3,105,C02,P04,2023-10-04 00:00:00,3,2000.0,Jane Smith,London,Keyboard,Electronics
4,106,C04,P02,2023-10-05 00:00:00,1,150.0,Susan Lee,Tokyo,Mouse,Electronics
5,107,C05,P05,2023-10-05 00:00:00,1,300.0,NaN,NaN,Pen,Stationery
6,108,C03,P02,2023-10-06 00:00:00,2,150.0,Peter Jones,New York,Mouse,Electronics
7,109,C01,P04,2023-10-07,1,2000.0,John Doe,New York,Keyboard,Electronics
8,110,C04,P03,2023-10-08,2,1200.0,Susan Lee,Tokyo,Book,Stationery

##### **Exercise 8: Finding Unsold Products**

In [76]:
# 1
unsold_products = pd.merge(df_orders[['product_id']],
                           df_products, on='product_id', how='right')
unsold_products = unsold_products[unsold_products['product_name'].isna()]
unsold_products

Empty DataFrame
Columns: [product_id, product_name, category]
Index: []

##### **Exercise 9: Dropping Duplicates**

In [79]:
# 1
df_merged = pd.concat([df_merged, df_merged.tail(1)])
df_merged

,order_id,customer_id,product_id,order_date,quantity,price_per_item,customer_name,city,product_name,category
0,101,C01,P01,2023-10-01 00:00:00,2,500.0,John Doe,New York,Laptop,Electronics
1,103,C01,P02,2023-10-02 00:00:00,5,150.0,John Doe,New York,Mouse,Electronics
2,104,C03,P01,2023-10-03 00:00:00,1,500.0,Peter Jones,New York,Laptop,Electronics
3,105,C02,P04,2023-10-04 00:00:00,3,2000.0,Jane Smith,London,Keyboard,Electronics
4,106,C04,P02,2023-10-05 00:00:00,1,150.0,Susan Lee,Tokyo,Mouse,Electronics
5,107,C05,P05,2023-10-05 00:00:00,1,300.0,NaN,NaN,Pen,Stationery
6,108,C03,P02,2023-10-06 00:00:00,2,150.0,Peter Jones,New York,Mouse,Electronics
7,109,C01,P04,2023-10-07,1,2000.0,John Doe,New York,Keyboard,Electronics
8,110,C04,P03,2023-10-08,2,1200.0,Susan Lee,Tokyo,Book,Stationery
8,110,C04,P03,2023-10-08,2,1200.0,Susan Lee,Tokyo,Book,Stationery

In [ ]:
# 2
df_merged = df_merged.drop_duplicates()
df_merged

,order_id,customer_id,product_id,order_date,quantity,price_per_item,customer_name,city,product_name,category
0,101,C01,P01,2023-10-01 00:00:00,2,500.0,John Doe,New York,Laptop,Electronics
1,103,C01,P02,2023-10-02 00:00:00,5,150.0,John Doe,New York,Mouse,Electronics
2,104,C03,P01,2023-10-03 00:00:00,1,500.0,Peter Jones,New York,Laptop,Electronics
3,105,C02,P04,2023-10-04 00:00:00,3,2000.0,Jane Smith,London,Keyboard,Electronics
4,106,C04,P02,2023-10-05 00:00:00,1,150.0,Susan Lee,Tokyo,Mouse,Electronics
5,107,C05,P05,2023-10-05 00:00:00,1,300.0,NaN,NaN,Pen,Stationery
6,108,C03,P02,2023-10-06 00:00:00,2,150.0,Peter Jones,New York,Mouse,Electronics
7,109,C01,P04,2023-10-07,1,2000.0,John Doe,New York,Keyboard,Electronics
8,110,C04,P03,2023-10-08,2,1200.0,Susan Lee,Tokyo,Book,Stationery

##### **Exercise 10: Final Analysis Questions**

In [ ]:
# 1
df_merged['total_price'] = df_merged['quantity'] * df_merged['price_per_item']
df_merged

/var/folders/bg/hsvxykxj7yx0jz1nrhc3k6z40000gn/T/ipykernel_1136/2226748010.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged['total_price'] = df_merged['quantity'] * df_merged['price_per_item']

,order_id,customer_id,product_id,order_date,quantity,price_per_item,customer_name,city,product_name,category,total_price
0,101,C01,P01,2023-10-01 00:00:00,2,500.0,John Doe,New York,Laptop,Electronics,1000.0
1,103,C01,P02,2023-10-02 00:00:00,5,150.0,John Doe,New York,Mouse,Electronics,750.0
2,104,C03,P01,2023-10-03 00:00:00,1,500.0,Peter Jones,New York,Laptop,Electronics,500.0
3,105,C02,P04,2023-10-04 00:00:00,3,2000.0,Jane Smith,London,Keyboard,Electronics,6000.0
4,106,C04,P02,2023-10-05 00:00:00,1,150.0,Susan Lee,Tokyo,Mouse,Electronics,150.0
5,107,C05,P05,2023-10-05 00:00:00,1,300.0,NaN,NaN,Pen,Stationery,300.0
6,108,C03,P02,2023-10-06 00:00:00,2,150.0,Peter Jones,New York,Mouse,Electronics,300.0
7,109,C01,P04,2023-10-07,1,2000.0,John Doe,New York,Keyboard,Electronics,2000.0
8,110,C04,P03,2023-10-08,2,1200.0,Susan Lee,Tokyo,Book,Stationery,2400.0

In [ ]:
# 2
total_rev_elect = df_merged[df_merged['category'] == 'Electronics']['total_price'].sum()
total_rev_elect

10700.0

##### **Challenge: Try to solve the following question without using .groupby().**

In [ ]:
# 3
customer_spending = {}
for customer_id in df_merged['customer_id'].unique():
    customer_spending[customer_id] = df_merged[df_merged['customer_id'] == customer_id]['total_price'].sum()

for customer, spend in customer_spending.items():
    print(f"Customer {customer}: ${spend:,.2f}")

Customer C01: $3,750.00
Customer C03: $800.00
Customer C02: $6,000.00
Customer C04: $2,550.00
Customer C05: $300.00

In [86]:
# 4
product_rev = {}
for name in df_merged['product_name'].unique():
    product_rev[name] = df_merged[df_merged['product_name'] == name]['total_price'].sum()

max_product = max(product_rev.items(), key=lambda x: x[1])
print(max_product)

('Keyboard', 8000.0)

In [89]:
# 5
category_rev = {}
for name in df_merged['category'].unique():
    category_rev[name] = df_merged[df_merged['category'] == name]['total_price'].sum()

min_category = min(category_rev.items(), key=lambda x: x[1])
print(min_category)

('Stationery', 2700.0)

In [90]:
# 6
city_rev = {}
for name in df_merged['city'].unique():
    city_rev[name] = df_merged[df_merged['city'] == name]['total_price'].mean()

highest_avg_city = max(city_rev.items(), key=lambda x: x[1])
print(highest_avg_city)

('London', 6000.0)

In [4]:
3 > 2 > 1

True