#### Name: Nguyen Thi Thu Trang
#### Class: DSEB65A
#### Student ID: 11230595
#### Homework 3

In [ ]:
df_stock.head()

In [32]:
import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt

In [33]:
# Set a nicer style for plots
sns.set_style("whitegrid")

# Load the Tips dataset
tips = sns.load_dataset('tips')

# Load the Online Retail dataset from URL
retail = pd.read_excel('/Users/thutrang/Desktop/Code/NEU/DataPrepVisualize/Data/Online Retail.xlsx')

In [34]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [35]:
retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

##### **Exercise 1: Basic Statistics on the Tips Dataset**

In [36]:
# a
sum(tips['total_bill'])

4827.7699999999995

In [37]:
# b
tips['tip'].mean()

2.99827868852459

In [38]:
# c
tips['size'].max()

6

##### **Exercise 2: Grouping by a Single Column**

In [39]:
# a 
for day in tips['day'].unique():
    total_bill_each_day = tips[tips['day'] == day]['total_bill'].sum()
    print(f"Day {day} has total bill: {total_bill_each_day}")

Day Sun has total bill: 1627.16
Day Sat has total bill: 1778.3999999999999
Day Thur has total bill: 1096.33
Day Fri has total bill: 325.88

In [40]:
# b 
# Sunday has the highest total revenue

##### **Exercise 3: Using aggregate()**

In [41]:
tips.groupby('day')['tip'].mean()

/var/folders/bg/hsvxykxj7yx0jz1nrhc3k6z40000gn/T/ipykernel_2643/326588963.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby('day')['tip'].mean()

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

In [42]:
tips.groupby('day')['tip'].max()

/var/folders/bg/hsvxykxj7yx0jz1nrhc3k6z40000gn/T/ipykernel_2643/2859609296.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby('day')['tip'].max()

day
Thur     6.70
Fri      4.73
Sat     10.00
Sun      6.50
Name: tip, dtype: float64

##### **Exercise 4: Grouping by Multiple Columns**

In [43]:
tips.groupby(by=['sex', 'smoker'])['tip'].sum()

/var/folders/bg/hsvxykxj7yx0jz1nrhc3k6z40000gn/T/ipykernel_2643/298606671.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby(by=['sex', 'smoker'])['tip'].sum()

sex     smoker
Male    Yes       183.07
        No        302.00
Female  Yes        96.74
        No        149.77
Name: tip, dtype: float64

##### **Exercise 5: Filtering Groups**

In [44]:
tips.groupby('day').filter(lambda x: x['tip'].sum() > 100)['day'].unique()

/var/folders/bg/hsvxykxj7yx0jz1nrhc3k6z40000gn/T/ipykernel_2643/3774255948.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby('day').filter(lambda x: x['tip'].sum() > 100)['day'].unique()

['Sun', 'Sat', 'Thur']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

##### **Exercise 6: Transforming Groups**

In [45]:
tips['normalized_total_bill'] = (tips['total_bill'] - tips['total_bill'].mean()) / tips['total_bill'].std()

In [46]:
tips.head()

   total_bill   tip     sex smoker  day    time  size  normalized_total_bill
0       16.99  1.01  Female     No  Sun  Dinner     2              -0.314066
1       10.34  1.66    Male     No  Sun  Dinner     3              -1.061054
2       21.01  3.50    Male     No  Sun  Dinner     3               0.137497
3       23.68  3.31    Male     No  Sun  Dinner     2               0.437416
4       24.59  3.61  Female     No  Sun  Dinner     4               0.539635

##### **Exercise 7: Basic Pivot Table**

In [47]:
pd.pivot_table(tips, values='tip', index='day', columns='time', aggfunc='mean')

/var/folders/bg/hsvxykxj7yx0jz1nrhc3k6z40000gn/T/ipykernel_2643/3891507639.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(tips, values='tip', index='day', columns='time', aggfunc='mean')

time     Lunch    Dinner
day
Thur  2.767705  3.000000
Fri   2.382857  2.940000
Sat        NaN  2.993103
Sun        NaN  3.255132

##### **Exercise 8: Advanced Pivot Table**

In [48]:
pd.pivot_table(tips, values=['total_bill', 'tip'], index='sex', columns='smoker', margins=True, aggfunc='mean')

/var/folders/bg/hsvxykxj7yx0jz1nrhc3k6z40000gn/T/ipykernel_2643/1904218972.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(tips, values=['total_bill', 'tip'], index='sex', columns='smoker', margins=True, aggfunc='mean')

             tip                     total_bill
smoker       Yes        No       All        Yes         No        All
sex
Male    3.051167  3.113402  3.089618  22.284500  19.791237  20.744076
Female  2.931515  2.773519  2.833448  17.977879  18.105185  18.056897
All     3.008710  2.991854  2.998279  20.756344  19.188278  19.785943

##### **Exercise 9: Data Cleaning**

In [49]:
# a
retail = retail.dropna(subset='CustomerID')

In [50]:
retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [51]:
# b
cleaned_retail = retail[(retail['Quantity'] >= 0) & (retail['UnitPrice'] != 0)]

In [52]:
cleaned_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [53]:
# c 
pd.to_datetime(cleaned_retail['InvoiceDate'])

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 397884, dtype: datetime64[ns]

In [54]:
cleaned_retail.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397884 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397884 non-null  object
 1   StockCode    397884 non-null  object
 2   Description  397884 non-null  object
 3   Quantity     397884 non-null  int64
 4   InvoiceDate  397884 non-null  datetime64[ns]
 5   UnitPrice    397884 non-null  float64
 6   CustomerID   397884 non-null  float64
 7   Country      397884 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.3+ MB

In [55]:
# d 
cleaned_retail['TotalPrice'] = cleaned_retail['Quantity'] * cleaned_retail['UnitPrice']

/var/folders/bg/hsvxykxj7yx0jz1nrhc3k6z40000gn/T/ipykernel_2643/698609554.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_retail['TotalPrice'] = cleaned_retail['Quantity'] * cleaned_retail['UnitPrice']

In [56]:
cleaned_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

##### **Exercise 10: Best-Selling Product Analysis**

In [ ]:
# a
top_10_quantity = cleaned_retail.groupby('StockCode')['Quantity'].sum().sort_values(ascending=False).head(10)
print(top_10_quantity)

StockCode
23843     80995
23166     77916
84077     54415
22197     49183
85099B    46181
85123A    36782
84879     35362
21212     33693
23084     27202
22492     26076
Name: Quantity, dtype: int64

In [58]:
# b 
top_10_revenue = cleaned_retail.groupby('StockCode')['TotalPrice'].sum().sort_values(ascending=False).head(10)
top_10_revenue

StockCode
23843     168469.60
22423     142592.95
85123A    100603.50
85099B     85220.78
23166      81416.73
POST       77803.96
47566      68844.33
84879      56580.34
M          53779.93
23084      51346.20
Name: TotalPrice, dtype: float64

##### **Exercise 11: Revenue Analysis by Country**

In [59]:
# a 
total_by_country = cleaned_retail.groupby('Country')['TotalPrice'].sum()
total_by_country

Country
Australia                138521.310
Austria                   10198.680
Bahrain                     548.400
Belgium                   41196.340
Brazil                     1143.600
Canada                     3666.380
Channel Islands           20450.440
Cyprus                    13590.380
Czech Republic              826.740
Denmark                   18955.340
EIRE                     265545.900
European Community         1300.250
Finland                   22546.080
France                   209024.050
Germany                  228867.140
Greece                     4760.520
Iceland                    4310.000
Israel                     7221.690
Italy                     17483.240
Japan                     37416.370
Lebanon                    1693.880
Lithuania                  1661.060
Malta                      2725.590
Netherlands              285446.340
Norway                    36165.440
Poland                     7334.650
Portugal                  33439.890
RSA                        1002.310
Saudi Arabia                145.920
Singapore                 21279.290
Spain                     61577.110
Sweden                    38378.330
Switzerland               56443.950
USA                        3580.390
United Arab Emirates       1902.280
United Kingdom          7308391.554
Unspecified                2667.070
Name: TotalPrice, dtype: float64

In [ ]:
# b
total_by_country[total_by_country.index != 'United Kingdom'].sort_values(ascending=False).head(10)

Country
Netherlands    285446.34
EIRE           265545.90
Germany        228867.14
France         209024.05
Australia      138521.31
Spain           61577.11
Switzerland     56443.95
Belgium         41196.34
Sweden          38378.33
Japan           37416.37
Name: TotalPrice, dtype: float64

##### **Exercise 12: Average Order Value (AOV) Analysis**

In [ ]:
# a
cleaned_retail.groupby('InvoiceNo')['TotalPrice'].sum()

InvoiceNo
536365    139.12
536366     22.20
536367    278.73
536368     70.05
536369     17.85
           ...
581583    124.60
581584    140.64
581585    329.05
581586    339.20
581587    249.45
Name: TotalPrice, Length: 18532, dtype: float64

In [88]:
# b
overall_aov = cleaned_retail.groupby('InvoiceNo')['TotalPrice'].sum().mean()
overall_aov

480.86595639974104

In [65]:
# c 
order_values = cleaned_retail.groupby(['Country', 'InvoiceNo'])['TotalPrice'].sum()
aov_by_country = order_values.groupby('Country').mean()
top_5_aov = aov_by_country[aov_by_country.index != 'United Kingdom'].sort_values(ascending=False).head(5)
top_5_aov

Country
Singapore      3039.898571
Netherlands    3036.663191
Australia      2430.198421
Japan          1969.282632
Lebanon        1693.880000
Name: TotalPrice, dtype: float64

##### **Exercise 13: Testing the 80/20 Principle (Customers and Products)**

In [67]:
# a 
customer_revenue = cleaned_retail.groupby('CustomerID')['TotalPrice'].sum().sort_values(ascending=False)
total_revenue = customer_revenue.sum()
cumulative_pct = (customer_revenue.cumsum() / total_revenue * 100)
customers_for_80 = len(cumulative_pct[cumulative_pct <= 80])
total_customers = len(customer_revenue)
pct_customers_for_80 = (customers_for_80 / total_customers) * 100
pct_customers_for_80

26.09497464269249

In [68]:
# b 
products_revenue = cleaned_retail.groupby('StockCode')['TotalPrice'].sum().sort_values(ascending=False)
total_rev_products = products_revenue.sum()
cumulative_pct_products = (products_revenue.cumsum() / total_rev_products * 100)
products_80 = len(cumulative_pct_products[cumulative_pct_products <= 80])
total_products = len(products_revenue)
pct_products_80 = (products_80 / total_products) * 100
pct_products_80

21.173260572987722

In [ ]:
# c 
''' 
Based on the results above (customers: 26% and products: 21%) -> 80/20 principle 
does not hole true for both in this dataset
'''

##### **Exercise 14: Market Basket Analysis and Product Recommendation**

In [ ]:
# a 
top_10_quantity

StockCode
23843     80995
23166     77916
84077     54415
22197     49183
85099B    46181
85123A    36782
84879     35362
21212     33693
23084     27202
22492     26076
Name: Quantity, dtype: int64

In [ ]:
# Choose target product: 23843

In [ ]:
# b
cleaned_retail[cleaned_retail['StockCode'] == 23843]['InvoiceNo']

540421    581483
Name: InvoiceNo, dtype: object

In [ ]:
# c
cleaned_retail[(cleaned_retail['InvoiceNo'] == 540421) | (cleaned_retail['InvoiceNo'] == 581483)]['StockCode']

540421    23843
Name: StockCode, dtype: object

In [81]:
# c 
cleaned_retail['StockCode'].value_counts().sort_values(ascending=False).head(5)

StockCode
85123A    2035
22423     1723
85099B    1618
84879     1408
47566     1396
Name: count, dtype: int64

In [ ]:
'''
The target product is not in the top 5 most frenquently bought.
'''

##### **Exercise 15: Analysis - Behavior of VIP Customerss**

In [83]:
# a
rev_by_customer = cleaned_retail.groupby('CustomerID')['TotalPrice'].sum()
rev_by_customer.quantile(0.95)

5841.842999999988

In [86]:
vip_customers = cleaned_retail[cleaned_retail['TotalPrice'] > rev_by_customer.quantile(0.95)]['CustomerID']
vip_customers

52711     15749.0
61619     12346.0
160546    15749.0
173382    16029.0
222680    15098.0
348325    17450.0
540421    16446.0
Name: CustomerID, dtype: float64

In [91]:
# b 
top_products = cleaned_retail[cleaned_retail['CustomerID'].isin(vip_customers)]['StockCode'].value_counts().sort_values(ascending=False).head(10)
top_products

StockCode
21181     20
21166     19
85099B    17
85152     16
22207     15
85099F    15
22386     14
82600     11
85123A    11
21175     11
Name: count, dtype: int64

In [89]:
# c 
vip_aov = cleaned_retail[cleaned_retail['CustomerID'].isin(vip_customers)].groupby('InvoiceNo')['TotalPrice'].sum().mean()
vip_aov

5132.902796610169

In [90]:
vip_aov > overall_aov

True

In [93]:
# d 
top_vip_products = cleaned_retail[cleaned_retail['CustomerID'].isin(vip_customers)][['StockCode', 'Description']].drop_duplicates()
top_vip_products = top_vip_products[top_vip_products['StockCode'].isin(top_products.index[:5])]

print("Proposed VIP Bundle based on most popular items:")
for _, row in top_vip_products.iterrows():
    print(f"- {row['Description']} (Code: {row['StockCode']})")

Proposed VIP Bundle based on most popular items:
- JUMBO BAG RED RETROSPOT (Code: 85099B)
- FRYING PAN UNION FLAG (Code: 22207)
- COOK WITH WINE METAL SIGN  (Code: 21166)
- HAND OVER THE CHOCOLATE   SIGN  (Code: 85152)
- PLEASE ONE PERSON METAL SIGN (Code: 21181)