In [ ]:
# pip install ucimlrepo

DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/PyEyeTrack-1.0.1-py3.12.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ucimlrepo) (2.2.3)
Requirement already satisfied: certifi>=2020.12.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ucimlrepo) (2024.8.30)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/thutrang/Library/Python/3.12/lib/python/site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.0.0->ucimlrepo) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.0.0->ucimlrepo) (2025.1)
Requirement already satisfied: six>=1.5 in /Users/thutrang/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7
Note: you may need to restart the kernel to use updated packages.

In [1]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
online_retail = fetch_ucirepo(id=352) 
  
# data (as pandas dataframes) 
X = online_retail.data.features 
y = online_retail.data.targets 
  
# metadata 
print(online_retail.metadata) 
  
# variable information 
print(online_retail.variables)

{'uci_id': 352, 'name': 'Online Retail', 'repository_url': 'https://archive.ics.uci.edu/dataset/352/online+retail', 'data_url': 'https://archive.ics.uci.edu/static/public/352/data.csv', 'abstract': 'This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.', 'area': 'Business', 'tasks': ['Classification', 'Clustering'], 'characteristics': ['Multivariate', 'Sequential', 'Time-Series'], 'num_instances': 541909, 'num_features': 6, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': None, 'index_col': ['InvoiceNo', 'StockCode'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2015, 'last_updated': 'Mon Oct 21 2024', 'dataset_doi': '10.24432/C5BW33', 'creators': ['Daqing Chen'], 'intro_paper': {'ID': 361, 'type': 'NATIVE', 'title': 'Data mining for the online retail industry: A case study of RFM model-based customer segmentation using data mining', 'authors': 'Daqing Chen, Sai Laing Sain, Kun Guo', 'venue': 'Journal of Database Marketing and Customer Strategy Management, Vol. 19, No. 3', 'year': 2012, 'journal': None, 'DOI': '10.1057/dbm.2012.17', 'URL': 'https://www.semanticscholar.org/paper/e43a5a90fa33d419df42e485099f8f08badf2149', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.The company mainly sells unique all-occasion gifts. Many customers of the company are wholesalers.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': "InvoiceNo: Invoice number. Nominal, a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter 'c', it indicates a cancellation. \nStockCode: Product (item) code. Nominal, a 5-digit integral number uniquely assigned to each distinct product.\nDescription: Product (item) name. Nominal.\nQuantity: The quantities of each product (item) per transaction. Numeric.\t\nInvoiceDate: Invoice Date and time. Numeric, the day and time when each transaction was generated.\nUnitPrice: Unit price. Numeric, Product price per unit in sterling.\nCustomerID: Customer number. Nominal, a 5-digit integral number uniquely assigned to each customer.\nCountry: Country name. Nominal, the name of the country where each customer resides. ", 'citation': None}}
          name     role         type demographic  \
0    InvoiceNo       ID  Categorical        None
1    StockCode       ID  Categorical        None
2  Description  Feature  Categorical        None
3     Quantity  Feature      Integer        None
4  InvoiceDate  Feature         Date        None
5    UnitPrice  Feature   Continuous        None
6   CustomerID  Feature  Categorical        None
7      Country  Feature  Categorical        None

                                         description     units missing_values
0  a 6-digit integral number uniquely assigned to...      None             no
1  a 5-digit integral number uniquely assigned to...      None             no
2                                       product name      None             no
3  the quantities of each product (item) per tran...      None             no
4  the day and time when each transaction was gen...      None             no
5                             product price per unit  sterling             no
6  a 5-digit integral number uniquely assigned to...      None             no
7  the name of the country where each customer re...      None             no

In [7]:
X

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...
541904,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [13]:
y

In [10]:
X.dtypes

Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [2]:
import pandas as pd

In [5]:
online_retail2 = pd.read_excel("/Users/thutrang/Desktop/Code/NEU/DataPrepVisualize/Data/OnlineRetail2.xlsx")
online_retail2

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [6]:
import numpy as np

In [20]:
data = {'Name': ['John', 'Anna', 'Peter', 'Linda', 'James'],
        'Age': [28, 22, np.nan, 32, 25],
        'City': ['New York', 'Paris', 'Berlin', np.nan, 'London'],
        'Salary': [70000, np.nan, 60000, 85000, np.nan]}
df = pd.DataFrame(data)

In [21]:
df

    Name   Age      City   Salary
0   John  28.0  New York  70000.0
1   Anna  22.0     Paris      NaN
2  Peter   NaN    Berlin  60000.0
3  Linda  32.0       NaN  85000.0
4  James  25.0    London      NaN

In [22]:
df.isnull()

    Name    Age   City  Salary
0  False  False  False   False
1  False  False  False    True
2  False   True  False   False
3  False  False   True   False
4  False  False  False    True

In [23]:
df['Salary'].fillna(value=df['Salary'].mean(), inplace=False)

0    70000.000000
1    71666.666667
2    60000.000000
3    85000.000000
4    71666.666667
Name: Salary, dtype: float64

In [19]:
df

    Name   Age      City        Salary
0   John  28.0  New York  70000.000000
1   Anna  22.0     Paris  71666.666667
2  Peter   NaN    Berlin  60000.000000
3  Linda  32.0       NaN  85000.000000
4  James  25.0    London  71666.666667

In [24]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],
                    columns=['letter', 'number'])
df1

  letter  number
0      a       1
1      b       2

In [26]:
df2 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
                    columns=['letter', 'number', 'animal'])
df2

  letter  number animal
0      c       3    cat
1      d       4    dog

In [27]:
pd.concat([df1, df2], axis=0, join='outer')

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

In [28]:
pd.concat([df1, df2], axis=0, join='inner')

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [29]:
pd.concat([df1, df2], axis=1, join='outer')

  letter  number letter  number animal
0      a       1      c       3    cat
1      b       2      d       4    dog

In [31]:
pd.concat([df1, df2], axis=1, join='inner', ignore_index=True)

   0  1  2  3    4
0  a  1  c  3  cat
1  b  2  d  4  dog

In [ ]:
pop = pd.read_csv("https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv")
pop.head()

     state/region     ages  year   population
0              AL  under18  2012    1117489.0
1              AL    total  2012    4817528.0
2              AL  under18  2010    1130966.0
3              AL    total  2010    4785570.0
4              AL  under18  2011    1125763.0
...           ...      ...   ...          ...
2539          USA    total  2010  309326295.0
2540          USA  under18  2011   73902222.0
2541          USA    total  2011  311582564.0
2542          USA  under18  2012   73708179.0
2543          USA    total  2012  313873685.0

[2544 rows x 4 columns]

In [46]:
areas = pd.read_csv("/Users/thutrang/Desktop/Code/NEU/DataPrepVisualize/Data/state-areas.csv")
areas.head()

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [42]:
abbrevs = pd.read_csv("https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv")
abbrevs.head()

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [50]:
df10 = areas.merge(abbrevs)
df10.head()

        state  area (sq. mi) abbreviation
0     Alabama          52423           AL
1      Alaska         656425           AK
2     Arizona         114006           AZ
3    Arkansas          53182           AR
4  California         163707           CA

In [52]:
final_df = pd.merge(df10, pop, how='inner', left_on='abbreviation', right_on='state/region')

In [53]:
final_df.head()

     state  area (sq. mi) abbreviation state/region     ages  year  population
0  Alabama          52423           AL           AL  under18  2012   1117489.0
1  Alabama          52423           AL           AL    total  2012   4817528.0
2  Alabama          52423           AL           AL  under18  2010   1130966.0
3  Alabama          52423           AL           AL    total  2010   4785570.0
4  Alabama          52423           AL           AL  under18  2011   1125763.0

In [54]:
df_2010 = final_df[final_df['year'] == 2010]

In [56]:
df_2010

,state,area (sq. mi),abbreviation,state/region,ages,year,population
2,Alabama,52423,AL,AL,under18,2010,1130966.0
3,Alabama,52423,AL,AL,total,2010,4785570.0
90,Alaska,656425,AK,AK,under18,2010,187902.0
91,Alaska,656425,AK,AK,total,2010,713868.0
100,Arizona,114006,AZ,AZ,under18,2010,1628563.0
...,...,...,...,...,...,...,...
2347,Wisconsin,65503,WI,WI,under18,2010,1336094.0
2356,Wyoming,97818,WY,WY,under18,2010,135351.0
2357,Wyoming,97818,WY,WY,total,2010,564222.0
2404,District of Columbia,68,DC,DC,under18,2010,101309.0
2405,District of Columbia,68,DC,DC,total,2010,605125.0

In [63]:
df_2010['density'] = df_2010['population'] / df_2010['area (sq. mi)']

/var/folders/bg/hsvxykxj7yx0jz1nrhc3k6z40000gn/T/ipykernel_2985/3010814147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2010['density'] = df_2010['population'] / df_2010['area (sq. mi)']

In [64]:
df_2010['rank'] = df_2010['density'].rank(ascending=False, method='dense')

/var/folders/bg/hsvxykxj7yx0jz1nrhc3k6z40000gn/T/ipykernel_2985/94835282.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2010['rank'] = df_2010['density'].rank(ascending=False, method='dense')

In [65]:
df_2010

,state,area (sq. mi),abbreviation,state/region,ages,year,population,rank,density
2,Alabama,52423,AL,AL,under18,2010,1130966.0,71.0,21.573851
3,Alabama,52423,AL,AL,total,2010,4785570.0,33.0,91.287603
90,Alaska,656425,AK,AK,under18,2010,187902.0,102.0,0.286251
91,Alaska,656425,AK,AK,total,2010,713868.0,101.0,1.087509
100,Arizona,114006,AZ,AZ,under18,2010,1628563.0,79.0,14.284889
...,...,...,...,...,...,...,...,...,...
2347,Wisconsin,65503,WI,WI,under18,2010,1336094.0,73.0,20.397447
2356,Wyoming,97818,WY,WY,under18,2010,135351.0,100.0,1.383702
2357,Wyoming,97818,WY,WY,total,2010,564222.0,94.0,5.768079
2404,District of Columbia,68,DC,DC,under18,2010,101309.0,2.0,1489.838235
2405,District of Columbia,68,DC,DC,total,2010,605125.0,1.0,8898.897059

In [68]:
df_2010.drop(columns=['abbreviation', 'ages'])

,state,area (sq. mi),state/region,year,population,rank,density
2,Alabama,52423,AL,2010,1130966.0,71.0,21.573851
3,Alabama,52423,AL,2010,4785570.0,33.0,91.287603
90,Alaska,656425,AK,2010,187902.0,102.0,0.286251
91,Alaska,656425,AK,2010,713868.0,101.0,1.087509
100,Arizona,114006,AZ,2010,1628563.0,79.0,14.284889
...,...,...,...,...,...,...,...
2347,Wisconsin,65503,WI,2010,1336094.0,73.0,20.397447
2356,Wyoming,97818,WY,2010,135351.0,100.0,1.383702
2357,Wyoming,97818,WY,2010,564222.0,94.0,5.768079
2404,District of Columbia,68,DC,2010,101309.0,2.0,1489.838235
2405,District of Columbia,68,DC,2010,605125.0,1.0,8898.897059

In [73]:
planets = pd.read_csv("/Users/thutrang/Desktop/Code/NEU/DataPrepVisualize/Data/planets.csv")

In [74]:
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [75]:
planets['number'].sum()

1848

In [76]:
planets['orbital_period'].mean()

2002.9175960947582

In [80]:
planets['method'].nunique()

10

In [81]:
planets['mass'].max()

25.0

In [82]:
planets['distance'].min()

1.35